# Generated by Django 4.2 on 2026-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("phoneNo", models.CharField(max_length=15)),
                ("appointmentDate", models.DateField()),
                ("symptoms", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=20)),
                ("add", models.TextField()),
                ("ename", models.CharField(max_length=30)),
                ("relation", models.CharField(max_length=30)),
                ("emergencynumber", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=20)),
                ("msg", models.TextField()),
            ],
        ),
    ]
