# Generated by Django 4.2 on 2026-04-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_emergencylog_tourist_delete_apps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourist",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SafetyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tourist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.tourist",
                    ),
                ),
            ],
        ),
    ]
