# Generated by Django 4.2 on 2026-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_tourist_password_safetylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourist",
            name="guardian_number",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tourist",
            name="tourist_number",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
